global:
    scrape_interval: 2s
    evaluation_interval: 2s

scrape_configs:
    - job_name: 'prometheus'
      metrics_path: '/metrics'
      scrape_interval: 5s
      static_configs:
        - targets: ['host.docker.internal:8889']